# Generated by Django 6.0 on 2026-01-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminlog_details_adminlog_is_flagged_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='action_type',
            field=models.CharField(help_text='Type of admin action (e.g. ROLE_UPDATED, USER_FLAGGED)', max_length=50),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='details',
            field=models.TextField(blank=True, help_text='Human readable explanation of the action', null=True),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Whether this log entry is flagged for review'),
        ),
    ]
