# Generated by Django 6.0 on 2026-01-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flag_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
